pool:
  vmImage: 'ubuntu-18.04'
variables:
  - group: GitHub
steps:
  - script: sudo apt update;sudo apt install -y git python-requests wget
    displayName: Instalação de dependências
  - script: bash website/download-counter/download-counter.sh
    displayName: Atualização do contador de downloads
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
- cron: "0 12 * * *"
  displayName: Daily midday build
  branches:
    include:
    - master
